spring:
  datasource:
    username: root
    password: prashantMac
    url: jdbc:mysql://localhost:3306/userdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
